# Generated by Django 4.2.11 on 2024-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mrp', models.CharField(max_length=10)),
                ('sp', models.CharField(blank=True, max_length=10, null=True)),
                ('presc', models.BooleanField(default=False)),
                ('manf', models.CharField(max_length=255)),
                ('sidef', models.TextField()),
                ('howtouse', models.TextField()),
                ('description', models.TextField()),
                ('therapyclass', models.CharField(max_length=255)),
            ],
        ),
    ]
