# Generated by Django 4.2.11 on 2024-04-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_medicine_inventory_inventory_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.inventory'),
        ),
    ]
