# Generated by Django 4.2.11 on 2024-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_inventory_medicine_medicine_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicines',
            field=models.ManyToManyField(to='api.medicine'),
        ),
    ]
