# Generated by Django 4.2.11 on 2024-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_medicine_inventory_inventory_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, to='api.medicine'),
        ),
    ]
